name: github pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    
    - name: setup node
      uses: actions/setup-node@v2.1.0
      with:
        node-version: '15.x'
      
    - name: install
      run: npm i
    
    - name: build
      run: |
        npm run build
        touch out/.nojekeyll
        
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3.6.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
